keywords:
  - ai
  - agent
  - claw
  - claude
  - skill
  - 智能体

organizations:
  - anthropic
  - openai
  - google-deepmind
  - meta
  - microsoft
  - nvidia
  - bytedance
  - langchain-ai
  - langgenius
  - n8n-io
  - cohere-ai
  - stability-ai
  - huggingface
  - togethercomputer
  - mozilla-ai

developers:
  - karpathy
  - swyx
  - garyyeh
  - mshumer
  - natfriedman
  - farzadpe
  - sigoden
  - e2b-dev
  - anthropics
