'use client';

import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sparkles, ExternalLink, Loader2, Download, FileText } from 'lucide-react';
import type { Repository } from '@/types';

interface SummaryModalProps {
  repo: Repository | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function SummaryModal({ repo, open, onOpenChange }: SummaryModalProps) {
  const [summary, setSummary] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchSummary = async () => {
    if (!repo) return;
    setLoading(true);
    setError(null);
    setSummary('');
    try {
      const resp = await fetch('/api/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          full_name: repo.full_name,
          description: repo.description,
          language: repo.language,
          topics: repo.topics,
        }),
      });
      const data = await resp.json();
      setSummary(data.summary || '暂无总结');
    } catch (e) {
      setError('请求失败，请检查网络连接');
    } finally {
      setLoading(false);
    }
  };

  const exportMarkdown = () => {
    if (!repo) return;
    
    const mdContent = `# ${repo.full_name}

${repo.description || '暂无描述'}

## 项目信息

- **地址**: ${repo.html_url}
- **语言**: ${repo.language || '未知'}
- **Star**: ${repo.stargazers_count.toLocaleString()}
- **Fork**: ${repo.forks_count.toLocaleString()}
- **创建时间**: ${repo.created_at}
${repo.topics?.length ? `\n## 标签\n\n${repo.topics.map(t => `- ${t}`).join('\n')}` : ''}

## AI 总结

${summary}

---
Generated by GitHub Monitor
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repo.name}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!repo) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3 min-w-0 flex-1">
              <img
                src={repo.owner.avatar_url}
                alt={repo.owner.login}
                className="w-10 h-10 rounded-full flex-shrink-0"
              />
              <div className="min-w-0">
                <DialogTitle className="truncate">{repo.full_name}</DialogTitle>
                <p className="text-sm text-gray-500 dark:text-gray-400 truncate mt-0.5">
                  {repo.description || '暂无描述'}
                </p>
              </div>
            </div>
            <a
              href={repo.html_url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 flex-shrink-0 ml-3"
            >
              <ExternalLink className="w-4 h-4 text-gray-500" />
            </a>
          </div>
        </DialogHeader>

        <DialogDescription>
          {!summary && !loading && !error && (
            <button
              onClick={fetchSummary}
              className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
            >
              <Sparkles className="w-5 h-5" />
              AI 智能总结
            </button>
          )}

          {loading && (
            <div className="flex flex-col items-center gap-3 py-6">
              <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
              <p className="text-sm text-gray-500 dark:text-gray-400">
                AI 正在分析项目内容...
              </p>
            </div>
          )}

          {error && (
            <div className="text-center py-4">
              <p className="text-red-500 mb-3">{error}</p>
              <button
                onClick={fetchSummary}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition-colors"
              >
                重试
              </button>
            </div>
          )}

          {summary && (
            <div className="space-y-3">
              <div className="flex items-center gap-2 mb-3">
                <Sparkles className="w-4 h-4 text-amber-500" />
                <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                  AI 总结
                </span>
              </div>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <div className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap">
                  {summary}
                </div>
              </div>
              <div className="pt-3 border-t border-gray-100 dark:border-gray-800 flex items-center justify-between">
                <div className="flex gap-2 text-xs text-gray-400">
                  {repo.language && <span>语言: {repo.language}</span>}
                  <span>Stars: {repo.stargazers_count.toLocaleString()}</span>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={exportMarkdown}
                    className="flex items-center gap-1.5 text-xs text-green-600 hover:text-green-700 dark:text-green-400"
                  >
                    <Download className="w-3.5 h-3.5" />
                    导出 MD
                  </button>
                  <button
                    onClick={fetchSummary}
                    className="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
                  >
                    重新生成
                  </button>
                </div>
              </div>
            </div>
          )}
        </DialogDescription>
      </DialogContent>
    </Dialog>
  );
}